version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    deeple:
      image: lonnrot/deep-oc-deeple
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    deeple-gpu:
      image: lonnrot/deep-oc-deeple:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    deeple-rclone:
      extends:
        service: deeple
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
